import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * PDF Generator Utility
 * Handles all PDF report generation with professional formatting
 */

// Test if jsPDF is working
console.log('jsPDF imported:', typeof jsPDF);
console.log('autoTable imported:', typeof autoTable);

// Helper function to format currency
const formatCurrency = (amount) => {
  return `Rs. ${parseFloat(amount).toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`;
};

// Helper function to format date
const formatDate = (date) => {
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
};

// Add header to PDF
const addHeader = (doc, title) => {
  const pageWidth = doc.internal.pageSize.width;
  
  // Company name/logo area
  doc.setFillColor(0, 77, 64); // Teal color
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  // Company name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Govimansala', 20, 15);
  
  // Tagline
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Agricultural Management System', 20, 23);
  
  // Report title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title, pageWidth - 20, 20, { align: 'right' });
  
  return 40; // Return Y position after header
};

// Add footer to PDF
const addFooter = (doc) => {
  const pageCount = doc.internal.getNumberOfPages();
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.setFont('helvetica', 'normal');
    
    // Page number
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    
    // Generated date
    doc.text(
      `Generated on ${formatDate(new Date())}`,
      20,
      pageHeight - 10
    );
    
    // Contact info
    doc.text('www.govimansala.lk', pageWidth - 20, pageHeight - 10, { align: 'right' });
  }
};

// Add metadata section
const addMetadata = (doc, startY, period) => {
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  
  const metadata = [
    ['Report Period:', period],
    ['Generated By:', 'Admin'],
    ['Generated On:', formatDate(new Date())]
  ];
  
  let y = startY;
  metadata.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 70, y);
    y += 6;
  });
  
  return y + 5;
};

/**
 * Generate User Report PDF
 */
export const generateUserReport = (options, period) => {
  try {
    console.log('Starting PDF generation...');
    console.log('Options:', options);
    console.log('Period:', period);
    
    const doc = new jsPDF();
    console.log('jsPDF instance created');
    
    let yPos = addHeader(doc, 'User Report');
  
  // Metadata
  yPos = addMetadata(doc, yPos, period);
  
  // Summary section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('User Statistics Summary', 20, yPos);
  yPos += 10;
  
  // Mock data - replace with actual data
  const userStats = [
    ['Total Farmers', '45', options.farmers ? '✓ Included' : '✗ Excluded'],
    ['Total Vendors', '30', options.vendors ? '✓ Included' : '✗ Excluded'],
    ['Total Drivers', '15', options.drivers ? '✓ Included' : '✗ Excluded'],
    ['Total QA Staff', '10', options.qaStaff ? '✓ Included' : '✗ Excluded']
  ];
  
  doc.autoTable({
    startY: yPos,
    head: [['User Type', 'Count', 'Status']],
    body: userStats,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 77, 64],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [224, 242, 241]
    }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Detailed breakdown if specific options selected
  if (options.farmers) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('Farmers Detailed Report', 20, yPos);
    yPos += 8;
    
    const farmerData = [
      ['F001', 'Kamal Perera', 'Matale', 'Active', '25 Products'],
      ['F002', 'Nimal Silva', 'Kandy', 'Active', '18 Products'],
      ['F003', 'Sunil Fernando', 'Gampaha', 'Active', '32 Products'],
      ['F004', 'Ravi Kumar', 'Kurunegala', 'Inactive', '12 Products'],
      ['F005', 'Anil Jayawardena', 'Anuradhapura', 'Active', '28 Products']
    ];
    
    doc.autoTable({
      startY: yPos,
      head: [['Farmer ID', 'Name', 'Location', 'Status', 'Products']],
      body: farmerData,
      theme: 'striped',
      headStyles: {
        fillColor: [39, 174, 96],
        textColor: [255, 255, 255]
      }
    });
    
    yPos = doc.lastAutoTable.finalY + 10;
  }
  
  if (options.vendors) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('Vendors Detailed Report', 20, yPos);
    yPos += 8;
    
    const vendorData = [
      ['V001', 'Fresh Mart', 'Colombo', 'Active', formatCurrency(125000)],
      ['V002', 'Organic Store', 'Kandy', 'Active', formatCurrency(98000)],
      ['V003', 'Green Grocers', 'Galle', 'Active', formatCurrency(156000)]
    ];
    
    doc.autoTable({
      startY: yPos,
      head: [['Vendor ID', 'Name', 'Location', 'Status', 'Monthly Sales']],
      body: vendorData,
      theme: 'striped',
      headStyles: {
        fillColor: [52, 152, 219],
        textColor: [255, 255, 255]
      }
    });
  }
  
  addFooter(doc);
  console.log('Saving PDF...');
  doc.save(`User_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  console.log('PDF saved successfully!');
  } catch (error) {
    console.error('Error generating PDF:', error);
    alert('Failed to generate PDF. Please check the console for details.');
  }
};

/**
 * Generate Order Report PDF
 */
export const generateOrderReport = (options, period) => {
  try {
    console.log('Generating Order Report PDF...');
    const doc = new jsPDF();
  let yPos = addHeader(doc, 'Order Report');
  
  yPos = addMetadata(doc, yPos, period);
  
  // Summary section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('Order Statistics Summary', 20, yPos);
  yPos += 10;
  
  const orderStats = [
    ['Total Orders', '123', formatCurrency(2547800)],
    ['Completed Orders', '98', formatCurrency(2125000)],
    ['Pending Orders', '15', formatCurrency(325000)],
    ['Processing Orders', '8', formatCurrency(82500)],
    ['Cancelled Orders', '2', formatCurrency(15300)]
  ];
  
  doc.autoTable({
    startY: yPos,
    head: [['Order Status', 'Count', 'Total Value']],
    body: orderStats,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 77, 64],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [224, 242, 241]
    }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  if (options.allOrders || options.completedOnly) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('Recent Orders', 20, yPos);
    yPos += 8;
    
    const orderData = [
      ['ORD001', 'Kamal Perera', '2024-10-15', 'Completed', formatCurrency(25000)],
      ['ORD002', 'Nimal Silva', '2024-10-16', 'Completed', formatCurrency(18500)],
      ['ORD003', 'Sunil Fernando', '2024-10-17', 'Processing', formatCurrency(32000)],
      ['ORD004', 'Ravi Kumar', '2024-10-18', 'Pending', formatCurrency(15200)],
      ['ORD005', 'Anil Jay', '2024-10-19', 'Completed', formatCurrency(42000)]
    ];
    
    doc.autoTable({
      startY: yPos,
      head: [['Order ID', 'Customer', 'Date', 'Status', 'Amount']],
      body: orderData,
      theme: 'striped',
      headStyles: {
        fillColor: [39, 174, 96],
        textColor: [255, 255, 255]
      }
    });
  }
  
  addFooter(doc);
  doc.save(`Order_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  console.log('Order Report PDF saved successfully!');
  } catch (error) {
    console.error('Error generating Order Report PDF:', error);
    alert('Failed to generate Order Report PDF. Please check the console for details.');
  }
};

/**
 * Generate Revenue Report PDF
 */
export const generateRevenueReport = (options, period) => {
  try {
    console.log('Generating Revenue Report PDF...');
    const doc = new jsPDF();
  let yPos = addHeader(doc, 'Revenue Report');
  
  yPos = addMetadata(doc, yPos, period);
  
  // Financial Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('Financial Summary', 20, yPos);
  yPos += 10;
  
  const revenueData = [
    ['Total Revenue', formatCurrency(2547800), '100%'],
    ['Items Subtotal', formatCurrency(2235000), '87.7%'],
    ['Service Charges (10%)', formatCurrency(223500), '8.8%'],
    ['Delivery Fees', formatCurrency(89300), '3.5%'],
    ['Farmer Earnings (Net)', formatCurrency(1985500), '78.0%'],
    ['Crate Charges Deducted', formatCurrency(49500), '1.9%']
  ];
  
  doc.autoTable({
    startY: yPos,
    head: [['Revenue Category', 'Amount', 'Percentage']],
    body: revenueData,
    theme: 'grid',
    headStyles: {
      fillColor: [243, 156, 18],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [255, 249, 230]
    },
    columnStyles: {
      1: { halign: 'right' },
      2: { halign: 'right' }
    }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  if (options.farmerEarnings) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('Farmer Earnings Breakdown', 20, yPos);
    yPos += 8;
    
    const farmerEarnings = [
      ['Kamal Perera', formatCurrency(125000), formatCurrency(5000), formatCurrency(120000)],
      ['Nimal Silva', formatCurrency(98000), formatCurrency(3920), formatCurrency(94080)],
      ['Sunil Fernando', formatCurrency(156000), formatCurrency(6240), formatCurrency(149760)],
      ['Ravi Kumar', formatCurrency(87500), formatCurrency(3500), formatCurrency(84000)]
    ];
    
    doc.autoTable({
      startY: yPos,
      head: [['Farmer Name', 'Gross Sales', 'Crate Charges', 'Net Earnings']],
      body: farmerEarnings,
      theme: 'striped',
      headStyles: {
        fillColor: [39, 174, 96],
        textColor: [255, 255, 255]
      },
      columnStyles: {
        1: { halign: 'right' },
        2: { halign: 'right' },
        3: { halign: 'right', fontStyle: 'bold' }
      }
    });
  }
  
  addFooter(doc);
  doc.save(`Revenue_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  console.log('Revenue Report PDF saved successfully!');
  } catch (error) {
    console.error('Error generating Revenue Report PDF:', error);
    alert('Failed to generate Revenue Report PDF. Please check the console for details.');
  }
};

/**
 * Generate Performance Report PDF
 */
export const generatePerformanceReport = (options, period) => {
  try {
    console.log('Generating Performance Report PDF...');
    const doc = new jsPDF();
  let yPos = addHeader(doc, 'Performance Report');
  
  yPos = addMetadata(doc, yPos, period);
  
  // KPI Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('Key Performance Indicators', 20, yPos);
  yPos += 10;
  
  const kpiData = [
    ['Average Delivery Time', '2.5 hours', '95% on-time'],
    ['QA Response Rate', '98%', 'Excellent'],
    ['Driver Efficiency', '92%', 'Good'],
    ['Customer Satisfaction', '4.6/5.0', 'Very Good'],
    ['Order Fulfillment Rate', '97%', 'Excellent']
  ];
  
  doc.autoTable({
    startY: yPos,
    head: [['Metric', 'Value', 'Rating']],
    body: kpiData,
    theme: 'grid',
    headStyles: {
      fillColor: [155, 89, 182],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [240, 230, 250]
    }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  if (options.deliveryPerformance) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('Delivery Performance Details', 20, yPos);
    yPos += 8;
    
    const deliveryData = [
      ['Driver A', '45 deliveries', '98% on-time', '4.8/5.0'],
      ['Driver B', '38 deliveries', '95% on-time', '4.6/5.0'],
      ['Driver C', '52 deliveries', '97% on-time', '4.7/5.0']
    ];
    
    doc.autoTable({
      startY: yPos,
      head: [['Driver', 'Total Deliveries', 'On-Time Rate', 'Rating']],
      body: deliveryData,
      theme: 'striped',
      headStyles: {
        fillColor: [243, 156, 18],
        textColor: [255, 255, 255]
      }
    });
  }
  
  addFooter(doc);
  doc.save(`Performance_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  console.log('Performance Report PDF saved successfully!');
  } catch (error) {
    console.error('Error generating Performance Report PDF:', error);
    alert('Failed to generate Performance Report PDF. Please check the console for details.');
  }
};

/**
 * Generate Inventory Report PDF
 */
export const generateInventoryReport = (options, period) => {
  try {
    console.log('Generating Inventory Report PDF...');
    const doc = new jsPDF();
  let yPos = addHeader(doc, 'Inventory Report');
  
  yPos = addMetadata(doc, yPos, period);
  
  // Inventory Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('Inventory Overview', 20, yPos);
  yPos += 10;
  
  const inventoryStats = [
    ['Total Products', '156', 'Active'],
    ['In Stock', '142', '91%'],
    ['Low Stock', '8', '5%'],
    ['Out of Stock', '6', '4%']
  ];
  
  doc.autoTable({
    startY: yPos,
    head: [['Category', 'Count', 'Status']],
    body: inventoryStats,
    theme: 'grid',
    headStyles: {
      fillColor: [231, 76, 60],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [255, 235, 235]
    }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  if (options.popularProducts) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('Top Selling Products', 20, yPos);
    yPos += 8;
    
    const popularProducts = [
      ['Carrots', '1,250 kg', formatCurrency(100000), '1st'],
      ['Cabbage', '980 kg', formatCurrency(58800), '2nd'],
      ['Tomatoes', '850 kg', formatCurrency(85000), '3rd'],
      ['Potatoes', '1,500 kg', formatCurrency(75000), '4th'],
      ['Onions', '720 kg', formatCurrency(64800), '5th']
    ];
    
    doc.autoTable({
      startY: yPos,
      head: [['Product', 'Quantity Sold', 'Revenue', 'Rank']],
      body: popularProducts,
      theme: 'striped',
      headStyles: {
        fillColor: [39, 174, 96],
        textColor: [255, 255, 255]
      },
      columnStyles: {
        2: { halign: 'right' }
      }
    });
  }
  
  addFooter(doc);
  doc.save(`Inventory_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  console.log('Inventory Report PDF saved successfully!');
  } catch (error) {
    console.error('Error generating Inventory Report PDF:', error);
    alert('Failed to generate Inventory Report PDF. Please check the console for details.');
  }
};

/**
 * Generate Custom Report PDF
 */
export const generateCustomReport = (options, period) => {
  try {
    console.log('Generating Custom Report PDF...');
    const doc = new jsPDF();
  let yPos = addHeader(doc, 'Custom Report');
  
  yPos = addMetadata(doc, yPos, period);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('Custom Report Configuration', 20, yPos);
  yPos += 10;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text('This report contains custom-selected data based on your specifications.', 20, yPos);
  yPos += 10;
  
  const configData = [
    ['Custom Fields', options.customFields ? 'Enabled' : 'Disabled'],
    ['Advanced Filters', options.advancedFilters ? 'Enabled' : 'Disabled'],
    ['Comparative Analysis', options.comparativeAnalysis ? 'Enabled' : 'Disabled'],
    ['Export Format', 'PDF']
  ];
  
  doc.autoTable({
    startY: yPos,
    head: [['Configuration', 'Status']],
    body: configData,
    theme: 'grid',
    headStyles: {
      fillColor: [22, 160, 133],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Sample custom data
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('Custom Data Analysis', 20, yPos);
  yPos += 8;
  
  const customData = [
    ['Metric 1', 'Value A', 'Category X', '85%'],
    ['Metric 2', 'Value B', 'Category Y', '92%'],
    ['Metric 3', 'Value C', 'Category Z', '78%']
  ];
  
  doc.autoTable({
    startY: yPos,
    head: [['Metric', 'Value', 'Category', 'Performance']],
    body: customData,
    theme: 'striped',
    headStyles: {
      fillColor: [22, 160, 133],
      textColor: [255, 255, 255]
    }
  });
  
  addFooter(doc);
  doc.save(`Custom_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  console.log('Custom Report PDF saved successfully!');
  } catch (error) {
    console.error('Error generating Custom Report PDF:', error);
    alert('Failed to generate Custom Report PDF. Please check the console for details.');
  }
};

export default {
  generateUserReport,
  generateOrderReport,
  generateRevenueReport,
  generatePerformanceReport,
  generateInventoryReport,
  generateCustomReport
};
