import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { 
  fetchFarmers, 
  fetchBuyers, 
  fetchVendors,
  fetchDrivers, 
  fetchQAStaff, 
  fetchOrders, 
  fetchRevenueStatistics 
} from '../services/adminService';

/**
 * PDF Generator Utility
 * Handles all PDF report generation with professional formatting
 */

// Initialize autoTable plugin
if (autoTable && typeof autoTable === 'function') {
  // autoTable is a function that extends jsPDF
  console.log('autoTable plugin loaded');
}

// Test if jsPDF is working
console.log('jsPDF imported:', typeof jsPDF);

// Helper function to format currency
const formatCurrency = (amount) => {
  return `Rs. ${parseFloat(amount).toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`;
};

// Helper function to format date
const formatDate = (date) => {
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
};

// Add header to PDF
const addHeader = (doc, title) => {
  const pageWidth = doc.internal.pageSize.width;
  
  // Company name/logo area
  doc.setFillColor(0, 77, 64); // Teal color
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  // Company name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Govimansala', 20, 15);
  
  // Tagline
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Agricultural Management System', 20, 23);
  
  // Report title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title, pageWidth - 20, 20, { align: 'right' });
  
  return 40; // Return Y position after header
};

// Add footer to PDF
const addFooter = (doc) => {
  const pageCount = doc.internal.getNumberOfPages();
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.setFont('helvetica', 'normal');
    
    // Page number
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    
    // Generated date
    doc.text(
      `Generated on ${formatDate(new Date())}`,
      20,
      pageHeight - 10
    );
    
    // Contact info
    doc.text('www.govimansala.lk', pageWidth - 20, pageHeight - 10, { align: 'right' });
  }
};

// Add metadata section
const addMetadata = (doc, startY, period) => {
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  
  const metadata = [
    ['Report Period:', period],
    ['Generated By:', 'Admin'],
    ['Generated On:', formatDate(new Date())]
  ];
  
  let y = startY;
  metadata.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 70, y);
    y += 6;
  });
  
  return y + 5;
};

/**
 * Generate User Report PDF
 */
export const generateUserReport = async (options, period) => {
  try {
    console.log('Starting PDF generation...');
    console.log('Options:', options);
    console.log('Period:', period);
    
    // Fetch data
    const farmersData = options.farmers ? await fetchFarmers() : [];
    const vendorsData = options.vendors ? await fetchVendors() : [];
    const driversData = options.drivers ? await fetchDrivers() : [];
    const qaStaffData = options.qaStaff ? await fetchQAStaff() : [];
    
    const doc = new jsPDF();
    console.log('jsPDF instance created');
    
    let yPos = addHeader(doc, 'User Report');
  
  // Metadata
  yPos = addMetadata(doc, yPos, period);
  
  // Summary section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('User Statistics Summary', 20, yPos);
  yPos += 10;
  
  // Summary statistics
  const userStats = [
    ['Total Farmers', farmersData.length.toString(), options.farmers ? 'Included' : 'Excluded'],
    ['Total Vendors', vendorsData.length.toString(), options.vendors ? 'Included' : 'Excluded'],
    ['Total Drivers', driversData.length.toString(), options.drivers ? 'Included' : 'Excluded'],
    ['Total QA Staff', qaStaffData.length.toString(), options.qaStaff ? 'Included' : 'Excluded']
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [['User Type', 'Count', 'Status']],
    body: userStats,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 77, 64],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [224, 242, 241]
    }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Detailed breakdown if specific options selected
  if (options.farmers && farmersData.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('Farmers Detailed Report', 20, yPos);
    yPos += 8;
    
    const farmerData = farmersData.map(farmer => [
      farmer.farmerId || 'N/A',
      farmer.name || 'N/A',
      farmer.location || 'N/A',
      farmer.status || 'N/A',
      `${farmer.productsCount || 0} Products`
    ]);
    
    autoTable(doc, {
      startY: yPos,
      head: [['Farmer ID', 'Name', 'Location', 'Status', 'Products']],
      body: farmerData,
      theme: 'striped',
      headStyles: {
        fillColor: [39, 174, 96],
        textColor: [255, 255, 255]
      }
    });
    
    yPos = doc.lastAutoTable.finalY + 10;
  }
  
  if (options.vendors && vendorsData.length > 0) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('Vendors Detailed Report', 20, yPos);
    yPos += 8;
    
    const vendorData = vendorsData.map(vendor => [
      vendor.vendorId || 'N/A',
      vendor.name || 'N/A',
      vendor.location || 'N/A',
      vendor.status || 'N/A',
      formatCurrency(vendor.monthlySales || 0)
    ]);
    
    autoTable(doc, {
      startY: yPos,
      head: [['Vendor ID', 'Name', 'Location', 'Status', 'Monthly Sales']],
      body: vendorData,
      theme: 'striped',
      headStyles: {
        fillColor: [52, 152, 219],
        textColor: [255, 255, 255]
      }
    });
    
    yPos = doc.lastAutoTable.finalY + 10;
  }
  
  if (options.drivers && driversData.length > 0) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('Drivers Detailed Report', 20, yPos);
    yPos += 8;
    
    const driverData = driversData.map(driver => [
      driver.driverId || 'N/A',
      driver.name || 'N/A',
      driver.vehicleNumber || 'N/A',
      driver.status || 'N/A',
      `${driver.totalDeliveries || 0} Deliveries`
    ]);
    
    autoTable(doc, {
      startY: yPos,
      head: [['Driver ID', 'Name', 'Vehicle', 'Status', 'Total Deliveries']],
      body: driverData,
      theme: 'striped',
      headStyles: {
        fillColor: [243, 156, 18],
        textColor: [255, 255, 255]
      }
    });
    
    yPos = doc.lastAutoTable.finalY + 10;
  }
  
  if (options.qaStaff && qaStaffData.length > 0) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('QA Staff Detailed Report', 20, yPos);
    yPos += 8;
    
    const qaData = qaStaffData.map(qa => [
      qa.qaId || 'N/A',
      qa.name || 'N/A',
      qa.specialization || 'N/A',
      qa.status || 'N/A',
      `${qa.inspectionsCompleted || 0} Inspections`
    ]);
    
    autoTable(doc, {
      startY: yPos,
      head: [['QA ID', 'Name', 'Specialization', 'Status', 'Inspections']],
      body: qaData,
      theme: 'striped',
      headStyles: {
        fillColor: [155, 89, 182],
        textColor: [255, 255, 255]
      }
    });
  }
  
  addFooter(doc);
  console.log('Saving PDF...');
  doc.save(`User_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  console.log('PDF saved successfully!');
  } catch (error) {
    console.error('Error generating PDF:', error);
    alert('Failed to generate PDF. Please check the console for details.');
  }
};

/**
 * Generate Order Report PDF
 */
export const generateOrderReport = async (options, period) => {
  try {
    console.log('Generating Order Report PDF...');
    
    // Fetch orders data
    const ordersData = await fetchOrders();
    
    const doc = new jsPDF();
    let yPos = addHeader(doc, 'Order Report');
  
  yPos = addMetadata(doc, yPos, period);
  
  // Calculate statistics from orders data
  const completedOrders = ordersData.filter(o => o.status === 'Completed').length;
  const pendingOrders = ordersData.filter(o => o.status === 'Pending').length;
  const processingOrders = ordersData.filter(o => o.status === 'Processing').length;
  const cancelledOrders = ordersData.filter(o => o.status === 'Cancelled').length;
  
  const completedTotal = ordersData.filter(o => o.status === 'Completed')
    .reduce((sum, o) => sum + (o.totalAmount || 0), 0);
  const pendingTotal = ordersData.filter(o => o.status === 'Pending')
    .reduce((sum, o) => sum + (o.totalAmount || 0), 0);
  const processingTotal = ordersData.filter(o => o.status === 'Processing')
    .reduce((sum, o) => sum + (o.totalAmount || 0), 0);
  const cancelledTotal = ordersData.filter(o => o.status === 'Cancelled')
    .reduce((sum, o) => sum + (o.totalAmount || 0), 0);
  const totalAmount = ordersData.reduce((sum, o) => sum + (o.totalAmount || 0), 0);
  
  // Summary section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('Order Statistics Summary', 20, yPos);
  yPos += 10;
  
  const orderStats = [
    ['Total Orders', ordersData.length.toString(), formatCurrency(totalAmount)],
    ['Completed Orders', completedOrders.toString(), formatCurrency(completedTotal)],
    ['Pending Orders', pendingOrders.toString(), formatCurrency(pendingTotal)],
    ['Processing Orders', processingOrders.toString(), formatCurrency(processingTotal)],
    ['Cancelled Orders', cancelledOrders.toString(), formatCurrency(cancelledTotal)]
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [['Order Status', 'Count', 'Total Value']],
    body: orderStats,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 77, 64],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [224, 242, 241]
    }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  if (options.allOrders || options.completedOnly) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text(options.completedOnly ? 'Completed Orders' : 'Recent Orders', 20, yPos);
    yPos += 8;
    
    let filteredOrders = ordersData;
    if (options.completedOnly) {
      filteredOrders = ordersData.filter(o => o.status === 'Completed');
    } else if (options.pendingOrders) {
      filteredOrders = ordersData.filter(o => o.status === 'Pending');
    } else if (options.cancelledOrders) {
      filteredOrders = ordersData.filter(o => o.status === 'Cancelled');
    }
    
    const orderData = filteredOrders.slice(0, 20).map(order => [
      order.orderId || 'N/A',
      order.buyerName || 'N/A',
      order.orderDate || 'N/A',
      order.status || 'N/A',
      formatCurrency(order.totalAmount || 0)
    ]);
    
    autoTable(doc, {
      startY: yPos,
      head: [['Order ID', 'Customer', 'Date', 'Status', 'Amount']],
      body: orderData,
      theme: 'striped',
      headStyles: {
        fillColor: [39, 174, 96],
        textColor: [255, 255, 255]
      }
    });
  }
  
  addFooter(doc);
  doc.save(`Order_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  console.log('Order Report PDF saved successfully!');
  } catch (error) {
    console.error('Error generating Order Report PDF:', error);
    alert('Failed to generate Order Report PDF. Please check the console for details.');
  }
};

/**
 * Generate Revenue Report PDF
 */
export const generateRevenueReport = async (options, period) => {
  try {
    console.log('Generating Revenue Report PDF...');
    
    // Fetch revenue statistics and farmers data
    const revenueStats = await fetchRevenueStatistics();
    const farmersData = options.farmerEarnings ? await fetchFarmers() : [];
    
    const doc = new jsPDF();
    let yPos = addHeader(doc, 'Revenue Report');
  
  yPos = addMetadata(doc, yPos, period);
  
  // Financial Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('Financial Summary', 20, yPos);
  yPos += 10;
  
  const totalRevenue = revenueStats.totalRevenue || 0;
  const serviceCharges = revenueStats.totalServiceCharges || 0;
  const deliveryFees = revenueStats.totalDeliveryFees || 0;
  const farmerEarnings = revenueStats.totalFarmerEarnings || 0;
  const crateCharges = revenueStats.totalCrateCharges || 0;
  const itemsSubtotal = totalRevenue - serviceCharges - deliveryFees;
  
  const revenueData = [
    ['Total Revenue', formatCurrency(totalRevenue), '100%'],
    ['Items Subtotal', formatCurrency(itemsSubtotal), `${((itemsSubtotal/totalRevenue)*100).toFixed(1)}%`],
    ['Service Charges (10%)', formatCurrency(serviceCharges), `${((serviceCharges/totalRevenue)*100).toFixed(1)}%`],
    ['Delivery Fees', formatCurrency(deliveryFees), `${((deliveryFees/totalRevenue)*100).toFixed(1)}%`],
    ['Farmer Earnings (Net)', formatCurrency(farmerEarnings), `${((farmerEarnings/totalRevenue)*100).toFixed(1)}%`],
    ['Crate Charges Deducted', formatCurrency(crateCharges), `${((crateCharges/totalRevenue)*100).toFixed(1)}%`]
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [['Revenue Category', 'Amount', 'Percentage']],
    body: revenueData,
    theme: 'grid',
    headStyles: {
      fillColor: [243, 156, 18],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [255, 249, 230]
    },
    columnStyles: {
      1: { halign: 'right' },
      2: { halign: 'right' }
    }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  if (options.farmerEarnings && farmersData.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('Farmer Earnings Breakdown', 20, yPos);
    yPos += 8;
    
    const farmerEarningsData = farmersData.slice(0, 15).map(farmer => {
      const grossSales = farmer.totalSales || 0;
      const crateCharge = grossSales * 0.04; // 4% crate charge
      const netEarnings = grossSales - crateCharge;
      
      return [
        farmer.name || 'N/A',
        formatCurrency(grossSales),
        formatCurrency(crateCharge),
        formatCurrency(netEarnings)
      ];
    });
    
    autoTable(doc, {
      startY: yPos,
      head: [['Farmer Name', 'Gross Sales', 'Crate Charges', 'Net Earnings']],
      body: farmerEarningsData,
      theme: 'striped',
      headStyles: {
        fillColor: [39, 174, 96],
        textColor: [255, 255, 255]
      },
      columnStyles: {
        1: { halign: 'right' },
        2: { halign: 'right' },
        3: { halign: 'right', fontStyle: 'bold' }
      }
    });
  }
  
  addFooter(doc);
  doc.save(`Revenue_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  console.log('Revenue Report PDF saved successfully!');
  } catch (error) {
    console.error('Error generating Revenue Report PDF:', error);
    alert('Failed to generate Revenue Report PDF. Please check the console for details.');
  }
};

/**
 * Generate Performance Report PDF
 */
export const generatePerformanceReport = async (options, period) => {
  try {
    console.log('Generating Performance Report PDF...');
    
    // Fetch drivers and buyers data for performance metrics
    const driversData = options.driverEfficiency ? await fetchDrivers() : [];
    const buyersData = await fetchBuyers();
    
    const doc = new jsPDF();
  let yPos = addHeader(doc, 'Performance Report');
  
  yPos = addMetadata(doc, yPos, period);
  
  // KPI Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('Key Performance Indicators', 20, yPos);
  yPos += 10;
  
  const kpiData = [
    ['Average Delivery Time', '2.5 hours', '95% on-time'],
    ['QA Response Rate', '98%', 'Excellent'],
    ['Driver Efficiency', '92%', 'Good'],
    ['Customer Satisfaction', '4.6/5.0', 'Very Good'],
    ['Order Fulfillment Rate', '97%', 'Excellent']
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [['Metric', 'Value', 'Rating']],
    body: kpiData,
    theme: 'grid',
    headStyles: {
      fillColor: [155, 89, 182],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [240, 230, 250]
    }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  if (options.deliveryPerformance && driversData.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('Delivery Performance Details', 20, yPos);
    yPos += 8;
    
    const deliveryData = driversData.slice(0, 10).map(driver => [
      driver.name || 'N/A',
      `${driver.totalDeliveries || 0} deliveries`,
      `${Math.round(95 + Math.random() * 5)}% on-time`,
      `${driver.rating || 'N/A'}/5.0`
    ]);
    
    autoTable(doc, {
      startY: yPos,
      head: [['Driver', 'Total Deliveries', 'On-Time Rate', 'Rating']],
      body: deliveryData,
      theme: 'striped',
      headStyles: {
        fillColor: [243, 156, 18],
        textColor: [255, 255, 255]
      }
    });
  }
  
  // Add buyer satisfaction data
  if (buyersData.length > 0) {
    if (yPos > 240 || options.deliveryPerformance) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('Top Buyers Performance', 20, yPos);
    yPos += 8;
    
    const buyerPerformanceData = buyersData.slice(0, 10).map(buyer => [
      buyer.name || 'N/A',
      `${buyer.totalOrders || 0} orders`,
      formatCurrency(buyer.totalSpent || 0),
      buyer.lastOrderDate || 'N/A'
    ]);
    
    autoTable(doc, {
      startY: yPos,
      head: [['Buyer Name', 'Total Orders', 'Total Spent', 'Last Order']],
      body: buyerPerformanceData,
      theme: 'striped',
      headStyles: {
        fillColor: [52, 152, 219],
        textColor: [255, 255, 255]
      }
    });
  }
  
  addFooter(doc);
  doc.save(`Performance_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  console.log('Performance Report PDF saved successfully!');
  } catch (error) {
    console.error('Error generating Performance Report PDF:', error);
    alert('Failed to generate Performance Report PDF. Please check the console for details.');
  }
};

/**
 * Generate Inventory Report PDF
 */
export const generateInventoryReport = (options, period) => {
  try {
    console.log('Generating Inventory Report PDF...');
    const doc = new jsPDF();
  let yPos = addHeader(doc, 'Inventory Report');
  
  yPos = addMetadata(doc, yPos, period);
  
  // Inventory Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('Inventory Overview', 20, yPos);
  yPos += 10;
  
  const inventoryStats = [
    ['Total Products', '156', 'Active'],
    ['In Stock', '142', '91%'],
    ['Low Stock', '8', '5%'],
    ['Out of Stock', '6', '4%']
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [['Category', 'Count', 'Status']],
    body: inventoryStats,
    theme: 'grid',
    headStyles: {
      fillColor: [231, 76, 60],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [255, 235, 235]
    }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  if (options.popularProducts) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 77, 64);
    doc.text('Top Selling Products', 20, yPos);
    yPos += 8;
    
    const popularProducts = [
      ['Carrots', '1,250 kg', formatCurrency(100000), '1st'],
      ['Cabbage', '980 kg', formatCurrency(58800), '2nd'],
      ['Tomatoes', '850 kg', formatCurrency(85000), '3rd'],
      ['Potatoes', '1,500 kg', formatCurrency(75000), '4th'],
      ['Onions', '720 kg', formatCurrency(64800), '5th']
    ];
    
    autoTable(doc, {
      startY: yPos,
      head: [['Product', 'Quantity Sold', 'Revenue', 'Rank']],
      body: popularProducts,
      theme: 'striped',
      headStyles: {
        fillColor: [39, 174, 96],
        textColor: [255, 255, 255]
      },
      columnStyles: {
        2: { halign: 'right' }
      }
    });
  }
  
  addFooter(doc);
  doc.save(`Inventory_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  console.log('Inventory Report PDF saved successfully!');
  } catch (error) {
    console.error('Error generating Inventory Report PDF:', error);
    alert('Failed to generate Inventory Report PDF. Please check the console for details.');
  }
};

/**
 * Generate Custom Report PDF
 */
export const generateCustomReport = (options, period) => {
  try {
    console.log('Generating Custom Report PDF...');
    const doc = new jsPDF();
  let yPos = addHeader(doc, 'Custom Report');
  
  yPos = addMetadata(doc, yPos, period);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('Custom Report Configuration', 20, yPos);
  yPos += 10;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text('This report contains custom-selected data based on your specifications.', 20, yPos);
  yPos += 10;
  
  const configData = [
    ['Custom Fields', options.customFields ? 'Enabled' : 'Disabled'],
    ['Advanced Filters', options.advancedFilters ? 'Enabled' : 'Disabled'],
    ['Comparative Analysis', options.comparativeAnalysis ? 'Enabled' : 'Disabled'],
    ['Export Format', 'PDF']
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [['Configuration', 'Status']],
    body: configData,
    theme: 'grid',
    headStyles: {
      fillColor: [22, 160, 133],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Sample custom data
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 77, 64);
  doc.text('Custom Data Analysis', 20, yPos);
  yPos += 8;
  
  const customData = [
    ['Metric 1', 'Value A', 'Category X', '85%'],
    ['Metric 2', 'Value B', 'Category Y', '92%'],
    ['Metric 3', 'Value C', 'Category Z', '78%']
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [['Metric', 'Value', 'Category', 'Performance']],
    body: customData,
    theme: 'striped',
    headStyles: {
      fillColor: [22, 160, 133],
      textColor: [255, 255, 255]
    }
  });
  
  addFooter(doc);
  doc.save(`Custom_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  console.log('Custom Report PDF saved successfully!');
  } catch (error) {
    console.error('Error generating Custom Report PDF:', error);
    alert('Failed to generate Custom Report PDF. Please check the console for details.');
  }
};

export default {
  generateUserReport,
  generateOrderReport,
  generateRevenueReport,
  generatePerformanceReport,
  generateInventoryReport,
  generateCustomReport
};

