spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: supersecretkeysupersecretkeysupersecretkey
  expiration: 3600000

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security=DEBUG:


